### ISSUE TITLE
[Feature]Headland management setting

### ISSUE THREAD

**Issue by bullfarmer** [Courseplay/CourseGenerator#1]
**What is the problem this feature/enhancement solves?**
Im frustrated when you have square paddocks with ditches that you dont have an option to do the 1st headland smooth then sharp there afterwards to minimize corners not been planted for a tidier finish  

**Describe the solution you'd like**
1st headland to have smooth corners then sharp there afterwards

**Describe alternatives you've considered**
Just using smooth corners for headlands to stop the implement/tractor fall in the ditch or back into a tree etc. 

**Additional context**

**Comment by Tensuko** [comment]
![round corners](https://user-images.githubusercontent.com/27344744/204126896-18a8c1c0-e222-4824-b23a-db65ac138652.png)
![round pattern](https://user-images.githubusercontent.com/27344744/204126898-71558d46-b702-4dd6-8233-2a592b55e96e.png)

If you don't care much about the outer corners, try round corners and not smooth.

**Comment by rohne83** [comment]
This is indeed an issue which you even have with sharp headland corners currently. If a corner is not detected as sharp enough in the first headland, it won't ever be for any further headland (see Courseplay/CourseGenerator#3), and then you have the same missed spots there as with smooth headlands. For sharp corner setting I hope this will be solved in the future. But for smooth I'm not sure whether it's still self-explanatory if you integrate sharp corners also into this setting. Although I understand the point that on some fields it might be great to be able to have the outernmost lane worked just with smooth corners (to provide collisions with obstacles near field corners) and all subsequent headland lanes with sharp corners.

**Comment by andreasthu** [comment]
Sowas ähnliches hab ich schon in Courseplay/Courseplay_FS22#1924 angesprochen. Der Mähdrescher müsste beim zurücksetzen an der äußeren ecke nicht bis zum Feldrand zurück, sondern nur bis zur "Getreidekante". Dann ginge sich das auch mit Deichen aus. Wurde nur leider nicht verwirklicht.
Lg
Andreas

**Comment by Tensuko** [comment]
> Dann ginge sich das auch mit Deichen aus. Wurde nur leider nicht verwirklicht.

Weil es dafür das andere Wendemanöver gibt wenn man die Fruchtumfahrung aktiviert lässt.... dafür ist das da....

**Comment by rohne83** [comment]
> > Dann ginge sich das auch mit Deichen aus. Wurde nur leider nicht verwirklicht.
> 
> Weil es dafür das andere Wendemanöver gibt wenn man die Fruchtumfahrung aktiviert lässt.... dafür ist das da....

Du meinst Wenden auf dem Feld aktiviert? Für den ersten Drescher hab ich das in der Regel eh immer aktiviert, aber auch der lässt sich gerne noch durch Bäume am Feldrand blockieren (zumindest auf der Landkreis Rostock, wo MadMaxx es zugegebenermaßen mit den Bäumen etwas zu gut gemeint hat). Bei den nachfolgenden lass ichs gerne aus, weil die sonst auch dieses auf ihrer Bahn eigentlich unnötige Rückwärtsmaneuver hinlegen.
Ansonsten gehts aber halt auch nicht nur um Drescher, sondern es gibt ja auch noch Sämaschinen, Ballenpressen, etc. Die haben mitunter auch ihre Probleme mit Hindernissen bei scharfen Ecken, auch wenn das Wenden auf dem Feld aktiv ist. Von daher kann ich durchaus nachvollziehen, dass der Issueeröffner gerne nur die äußerste Vorgewendebahn weich, und alle inneren dann aber scharf bearbeitet haben möchte. 

So oder so hilft das aber alles nichts gegen die ausgelassenen Flecken wenn die Ecken einen derart ungünstigen Winkel haben, dass der Generator sie immer weich generiert (auch auf den inneren Bahnen), selbst wenn scharf eingestellt wurde.

**Comment by Tensuko** [comment]
> Von daher kann ich durchaus nachvollziehen, dass der Issueeröffner gerne nur die äußerste Vorgewendebahn weich, und alle inneren dann aber scharf bearbeitet haben möchte.

Meine Antwort bezog sich auf die Anfrage von Andreas, bzw sein altes Issue.
Die Idee mit dem gemischten Headland ist nicht so verkehrt.... aber Umsetzung....
Ich weis wie das läuft da macht man das erste rund und andere fix dann dauerts nicht lange dann wird gefragt nach den ersten 2 Vorgewende und schon wirds wieder unnötig komplex mit Settings etc und genau das wollen wir vermeiden.

Also einfach abwarten....

**Comment by coatsy35** [comment]
Could this be extended to force square corners on all corners as an addition to this if it's ever taken further? I find square corners where the old generator creates them are really good, but as said it doesn't' always do them depending on the angle, be nice to have the option to force the generation of square corners if wanted.

**Comment by pvaiko** [comment]
Not sure I understand what exactly you are looking for.

**Comment by coatsy35** [comment]
> Not sure I understand what exactly you are looking for.

Basically an option to force all corners of a field to use square corner nodes and only a curve if over a certain angle? i.e. an angle that works smoothly with the implement width selected

**Comment by pvaiko** [comment]
Oh, I see, that's implemented already in the new generator, although it is based on the turning radius, not the angle, see here: https://github.com/Courseplay/CourseGenerator/blob/ab7221fa387b5bbf080f9c35248af8015ea4ffee/CourseGenerator/geometry/Polyline.lua#L338

**Comment by coatsy35** [comment]
> Oh, I see, that's implemented already in the new generator, although it is based on the turning radius, not the angle, see here:
> 
> https://github.com/Courseplay/CourseGenerator/blob/ab7221fa387b5bbf080f9c35248af8015ea4ffee/CourseGenerator/geometry/Polyline.lua#L338

That sounds great. Can't wait for it to be released. I guess it's quite a while away yet! Something to look forward to.

**Comment by pvaiko** [comment]
Done, headlands can either be round or square, based on a turning radius. Also, number of headlands with round corner (from outside) can now be defined.
