### ISSUE TITLE
Somewhere in Thuringa Field 145 - Issue on the small "thingy" at the top left side

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/CourseGenerator#13]
With this settings we are getting a 100% coverage, however something looks wrong.
I also wonder about the generated turn, not sure how this would look like ingame and if tools can make it.
(may need to keep it like that, or do a generated loop as transition path?)
![grafik](https://github.com/Courseplay/CourseGenerator/assets/27344744/6fe63cdb-cd0d-42cd-89ba-ab8af8427193)

With a higher width I get no coverage there.
![grafik](https://github.com/Courseplay/CourseGenerator/assets/27344744/e4fa507e-45a8-45fe-8e3f-ca34e9ded973)

A crazy condition one... the unworked path with sharp corners could need a loop in the opposide direction instead of a sharp corner turn but with beeing worked on and not a transition. Not sure what would be the best solution.
![grafik](https://github.com/Courseplay/CourseGenerator/assets/27344744/94ead7b8-2baf-4f70-b5b6-fa07bc6ed237)

[debug.txt](https://github.com/Courseplay/CourseGenerator/files/12552647/debug.txt)

**Comment by Tensuko** [comment]
Played arround a bit more then just this screenshot, but in general it looks a lot better.
Just wonder what those 3 yellow does are.
![grafik](https://github.com/Courseplay/CourseGenerator/assets/27344744/7feaea98-dd3b-4ddf-9586-0d0323132add)

**Comment by pvaiko** [comment]
Yellow dots are corners (hover over them with mouse it'll show the properties). So that is something I need to take care of either in the generator or when actually running the course so the vehicle won't perform 3 headland turns there :)

**Comment by Tensuko** [comment]
Ok so I saw this triple turn right :)

**Comment by pvaiko** [comment]
This was fixed by 66d37beb
