### ISSUE TITLE
[Feature] Invert headland direction on islands

### ISSUE THREAD

**Issue by giorgiga** [Courseplay/CourseGenerator#19]
(Just an idea)

Since the only  (?) case where one cares about headland direction is when employing an asymmetric tool (eg. one of those windrowers which push the grass to one side), it could make sense to invert the headland direction when encircling islands (basically, turning "headland direction: clockwise/counterclockwise" into "side towards field: left/right")

**Comment by pvaiko** [comment]
There are two separate settings now, one for the headlands around the field and one for the headlands around islands, so it is completely customizable.

**Comment by giorgiga** [comment]
Thanks and sorry for the false report (the courseplay version on modhub is outdated)

**Comment by pvaiko** [comment]
(Note this is not part of the Courseplay mod yet, it'll take a few months until it is integrated)
